name: release-jobs
on:
  workflow_dispatch:
  pull_request:
    branches:
    - master

jobs:
  test-and-tag-release:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
    - name: Update PATH variable
      run: echo "$HOME/go/bin" >> $GITHUB_PATH
    - name: Check generated docs
      run: make check-docs
